/* The code is defining three arrays of objects: `sampleTags`, `sampleUsers`, and `sampleFoods`. These
arrays are used to store sample data for a food ordering application. `sampleTags` contains tags
that can be used to categorize food items, `sampleUsers` contains user data, and `sampleFoods`
contains information about different food items that can be ordered. */
export const sampleTags: any[] = [
  { name: "All", count: 14 },
  { name: "breakfast", count: 10 },
  { name: "lunch", count: 4 },
  { name: "dinner", count: 2 },
  { name: "fast-food", count: 6 },
  { name: "snack", count: 10 },
  { name: "beverage", count: 3 },
];

export const sampleUsers: any[] = [
  {
    name: "Alex Karanja",
    email: "alex@gmail.com",
    password: "12345",
    address: "Limuru",
    isAdmin: true,
  },
  {
    name: "Jane Muthoni",
    email: "jane@gmail.com",
    password: "54321",
    address: "Nairobi",
    isAdmin: false,
  },
];

export const sampleFoods: any[] = [
  {
    id: 1,
    name: "Chapati Wraps",
    price: 90,
    tags: ["breakfast", "lunch", "All", "dinner", "fast-food"],
    waitTime: "10min",
    imgUrl: "/assets/images/food-images/chapati-wraps.jpg",
    favorite: true,
    stars: 2.5,
    description: "Experience a flavor adventure with our fresh chapati wraps.",
  },
  {
    id: 2,
    name: "Fries",
    price: 150,
    tags: ["lunch", "dinner", "All", "fast-food"],
    waitTime: "25min",
    imgUrl: "/assets/images/food-images/fries.jpg",
    favorite: false,
    stars: 1.5,
    description: "Our fries are salted to perfection, a savory indulgence.",
  },
  {
    id: 3,
    name: "Coconut and Cinnamon Mandazi",
    price: 50,
    tags: ["breakfast", "snack", "All"],
    waitTime: "5min",
    imgUrl: "/assets/images/food-images/mandazi1.jpg",
    favorite: true,
    stars: 4.5,
    description: "Coconut-cinnamon twist on traditional mandazi.",
  },
  {
    id: 4,
    name: "Tea with Biscuits",
    price: 100,
    tags: ["breakfast", "beverage", "All"],
    waitTime: "5min",
    imgUrl: "/assets/images/food-images/tea-with-biscuits.jpg",
    favorite: false,
    stars: 4.5,
    description:
      "Locally sourced tea leaves, finely brewed with milk, served with biscuits",
  },
  {
    id: 5,
    name: "Vanilla Cake",
    price: 150,
    tags: ["breakfast", "snack", "All"],
    waitTime: "10min",
    imgUrl: "/assets/images/food-images/vanilla-cake1.jpg",
    favorite: true,
    stars: 4.5,
    description:
      "Experience sweetness and delight with our heavenly Vanilla Cakes",
  },
  {
    id: 6,
    name: "Coffee",
    price: 150,
    tags: ["breakfast", "beverage", "All"],
    waitTime: "5min",
    imgUrl: "/assets/images/food-images/coffee1.jpg",
    favorite: true,
    stars: 4.5,
    description: "Our coffee is a rich and bold delight.",
  },
  {
    id: 7,
    name: "Glazed Donuts",
    price: 150,
    tags: ["breakfast", "snack", "All"],
    waitTime: "5min",
    imgUrl: "/assets/images/food-images/glazed-donuts.jpg",
    favorite: true,
    stars: 4.5,
    description:
      "Tantalizing donuts with a glaze and topping of your choosing.",
  },
  {
    id: 8,
    name: "Yogurt",
    price: 250,
    tags: ["breakfast", "beverage", "snack", "All"],
    waitTime: "10min",
    imgUrl: "/assets/images/food-images/yorgut.jpg",
    favorite: true,
    stars: 4.5,
    description:
      "Rich, creamy yorgut expertly made in house from locally sourced milk.",
  },
  {
    id: 9,
    name: "Icecream",
    price: 180,
    tags: ["snack", "fast-food", "All"],
    waitTime: "15min",
    imgUrl: "/assets/images/food-images/icecream.jpg",
    favorite: true,
    stars: 4.5,
    description:
      "Our cool and refreshing sweet icecream is made from locally sourced milk.",
  },
  {
    id: 10,
    name: "Ham Sandwich",
    price: 80,
    tags: ["breakfast", "snack", "All", "fast-food"],
    waitTime: "20min",
    imgUrl: "/assets/images/food-images/sandwich.jpg",
    favorite: true,
    stars: 4.5,
    description: "Ham sandwich",
  },
  {
    id: 11,
    name: "Kebab",
    price: 150,
    tags: ["lunch", "snack", "fast-food", "All"],
    waitTime: "15min",
    imgUrl: "/assets/images/food-images/kebab.jpg",
    favorite: true,
    stars: 4.5,
    description: "Beef, mutton and chicken with vegetables on a stick.",
  },
  {
    id: 12,
    name: "Samosa",
    price: 70,
    tags: ["breakfast", "snack", "All"],
    waitTime: "10min",
    imgUrl: "/assets/images/food-images/samosa.jpg",
    favorite: true,
    stars: 4.5,
    description:
      "Swahili inspired samosas filled with beef, chalets and spring onions.",
  },
  {
    id: 13,
    name: "Hotdog",
    price: 250,
    tags: ["lunch", "snack", "fast-food", "All"],
    waitTime: "25min",
    imgUrl: "/assets/images/food-images/hotdog.jpg",
    favorite: true,
    stars: 4.5,
    description: "German style weiners on a soft bun.",
  },
  {
    id: 14,
    name: "Lemon Cake",
    price: 150,
    tags: ["breakfast", "snack", "All"],
    waitTime: "10min",
    imgUrl: "/assets/images/food-images/vanilla-cake2.jpg",
    favorite: true,
    stars: 4.5,
    description:
      "Experience sweetness and delight with our heavenly Lemon Cakes",
  },
];
